### ISSUE TITLE
Text freezes when losing in a random robattle

### ISSUE THREAD

**Issue by Blaziken257** [Medabots/medarot3#174]
## Version

Seen in the nightly build [0.3.2+EN+nightly.20230422](https://github.com/Medabots/medarot3/releases/tag/0.3.2%2BEN%2Bnightly.20230422), but also seen in the latest build when pulling the latest changes (as of April 26, 2023) 

## Description 
When a robattle starts from a random encounter, and you lose it, the text that appears freezes before it finishes printing, and hangs, making it impossible for the player to advance to the next screen. When this happens, VRAM 1:8800-97FF is written to continuously, and it also wraps around indefinitely. This continues until the player hard or soft resets the game.

This was tested in a couple of opponents (Office worker and Vehicle Medarot) but possibly occurs with other opponents. In each case, the glitch starts after printing 9 characters. However, this bug does _not_ occur with the very first battle.

This issue can be seen in both BGB and on real hardware using an Everdrive X7.

## Screenshots

![Medarot 3 Robattle Freeze 1](https://user-images.githubusercontent.com/2187686/234753294-5a2cf8f9-91e2-4677-a38c-5b6758baa36f.png) ![Medarot 3 Robattle Freeze 2](https://user-images.githubusercontent.com/2187686/234753307-85c2e27b-7f67-4ffe-9e68-2daff149ea60.png) ![Medarot 3 Robattle Freeze 3](https://user-images.githubusercontent.com/2187686/234753315-31ce5fd5-e800-4cee-a326-76e875bc975e.png)

Above: example screenshots of the text being corrupted. Notice even the border is eventually corrupted.

![Medarot 3 Robattle Iwanoi Wins](https://user-images.githubusercontent.com/2187686/234753501-1aa99433-1cbe-4197-a60a-576ac838a9cf.png)

Above: Notice that the text when losing against Iwanoi (at the very beginning of the game) has no issues.

## VRAM

![Medarot 3 Robattle Freeze VRAM](https://user-images.githubusercontent.com/2187686/234753637-ed6a0aca-fc5a-4909-a909-921db27fdf49.png)

VRAM in BGB while this issue occurs. Notice that "Office wo" shows up multiple times!

## Save / Save States

Attached to this issue.

The save state was from BGB 1.5.10 (most recent as of April 26, 2023) and is meant for Kabuto build 0.3.2+EN+nightly.20230422. This is in a robattle in a losing state. Pick any move to see the issue. A save file is also attached (just in case).
[Medarot 3 - Kabuto Version (Japan) (Beta 0.3.2-20230422).zip](https://github.com/Medabots/medarot3/files/11339352/Medarot.3.-.Kabuto.Version.Japan.Beta.0.3.2-20230422.zip)

**Comment by VariantXYZ** [comment]
I'm going to assume it's this line:

```
"みかたの リーダーの
きのうが ていしした!

そこまでっ!
勝者 <&BUF02>!"   "Function ceased!

That's it!
<&BUF02> wins!"
```

**Comment by VariantXYZ** [comment]
![image](https://github.com/Medabots/medarot3/assets/3066132/0d2264e3-9019-4db8-922d-96a77ca94873)

Fixed.
