### ISSUE TITLE
Text freezes when time is up in a Robattle and losing

### ISSUE THREAD

**Issue by Blaziken257** [Medabots/medarot3#177]
### Version

First seen in the nightly build [0.4.0+EN+nightly.20230608](https://github.com/Medabots/medarot3/releases/tag/0.4.0%2BEN%2Bnightly.20230608) and remains in [0.4.0+EN+nightly.20230609](https://github.com/Medabots/medarot3/releases/tag/0.4.0%2BEN%2Bnightly.20230609)

### Description

This issue is very similar to the now fixed issue #174. While the issue was partially fixed when your Medabot is defeated from its head being destroyed, it still occurs when time is up and losing.

This issue does not occur when time is up and winning.

It is easiest to reproduce by setting the Robattle Time to Short in the options (on the menu right after the title screen) but this is optional. While in a robattle, it is easiest to reproduce by stalling (e.g. by not dealing damage in some way) and taking damage but surviving when time is up.

### Screenshot

![bgb01096](https://github.com/Medabots/medarot3/assets/2187686/a501f1ff-c8eb-405e-9800-73984b21ebbf)

### Save / Save States

The save state is for BGB 1.5.10 on Medarot 3 Kabuto on 0.4.0+EN+nightly.20230609.
(A save file is also attached just in case it is necessary.)

[Medarot 3 - Kabuto Version (Japan) (Beta 0.4.0-20230609).zip](https://github.com/Medabots/medarot3/files/11709517/Medarot.3.-.Kabuto.Version.Japan.Beta.0.4.0-20230609.zip)

**Comment by VariantXYZ** [comment]
0B:55CF copies the 'winner' into BUF02.

If the player wins, it's C656 (the player name).

If they lose, it's C5A5, which is apparently empty in the patch...

**Comment by VariantXYZ** [comment]
Oh, it's because the previous fix in #174 set it up to store the index and load from there. Woops. This should work well though...
