### ISSUE TITLE
Translate the Game Over screen

### ISSUE THREAD

**Issue by Blaziken257** [Medabots/medarot3#178]
The Game Over screen is not yet translated. (It might need a custom font specific to this screen.)

It can be reached by losing parts to the point where you don't have enough for a single Medabot. This is possible as early as the first Robattle.

(Or you can hack your way here by setting RAM address C480 to 06 and C481 to 00. Ideally do this on a screen where textbox graphics are present in VRAM.)

![Game Over](https://github.com/Medabots/medarot3/assets/2187686/ff24fae6-7f99-4319-9c83-d3c6e3a35462)

**Comment by VariantXYZ** [comment]
Tileset3A73
Tilemap 012C
Attribmap 0031

**Comment by VariantXYZ** [comment]
Fixed by #181
