### ISSUE TITLE
Translate the Test Mode screen

### ISSUE THREAD

**Issue by Blaziken257** [Medabots/medarot3#179]
There is a Test Mode screen that is accessible from the title screen if the user presses A or Start, and holds Select before the fade out is finished. (Similar screens exist in other Medarot games which are accessed similarly.) This contains a music/sound test and an option to erase saved data.

This screen is not translated in the English patch and contains garbled text. The character mapping is unchanged from the retail Japanese game, while using the English tileset.

There doesn't appear to be any strings for this present in any of the CSV files (at least when using the grep command to search for them), so these strings should be added.

| Japanese | English |
| ------------- | ------------- |
| ![Test Mode (Japanese)](https://github.com/Medabots/medarot3/assets/2187686/6eac627e-a1ae-4f24-8aff-e33ccb8a53bb) | ![bgb01105](https://github.com/Medabots/medarot3/assets/2187686/582e6fee-86a3-4c7b-977b-3479ad3a377b) |

**Comment by VariantXYZ** [comment]
Attribute Map 011E
Tilemap 011C
