### ISSUE TITLE
Translate the save corruption screen

### ISSUE THREAD

**Issue by Blaziken257** [Medabots/medarot3#180]
Medarot 3 uses a checksum to verify if a save is corrupted or not. If the checksum fails, an error message appears telling stating that the data is corrupt and tells the user to restart from the beginning.

Relevant SRAM addresses:

- `0:A000-A00F`: ASCII header (` MEDAROT3      \00`) to verify if a save exists. If a cartridge is brand new, this string is not present. This ASCII string is the same in both Kabuto and Kuwagata versions.
- `0:A000-BFEF`: Checksum region
- `0:BFFE-BFFF`: 16-bit big endian checksum

To view the save corruption screen:

1. Optionally backup your save file first if you don't want to lose it.
2. In BGB, with the game running and the debugger open, right-click anywhere in the SRAM region (A000-BFFF) and check "Force memory visibility". Do not advance past the title screen yet.
3. Change one byte in either the checksum region after the ASCII header (from 0:A010-BFEF) or the checksum itself. (Do not change the ASCII header as the cartridge is assumed to be brand new if this is done, and will erase without any error message.)
4. Now advance past the title screen. A save corruption screen should appear. After A is pressed on this screen, the save will be erased.
5. After seeing this screen, you can restore your backup from step 1.

The save corruption screen is not translated in the English patch yet. Even if there is no software issue that can corrupt saved data, it can still happen due to hardware reasons, such as a dying battery.

| Japanese | English |
| ------------- | ------------- |
| ![Medarot 3 Save Corruption (Japanese)](https://github.com/Medabots/medarot3/assets/2187686/16f4c614-0059-486a-93b0-277f0742e1b7) | ![Medarot 3 Save Corruption (English)](https://github.com/Medabots/medarot3/assets/2187686/6ea99b2d-0250-4190-befa-25bc34956c25) |

Telefang has a very similar save corruption screen which can be accessed the same exact way. The Japanese text is the same (barring a typo in Telefang), and this is already translated in the Telefang English patch, so the Telefang translation could be reused for Medarot 3.

| Japanese (Power/Speed) | English (Power) |
| ------------- | ------------- |
| ![Telefang Save Corruption (Japanese)](https://github.com/Medabots/medarot3/assets/2187686/143f345d-9be8-4ad7-bfd1-1cfb13608f2a) | ![Telefang Save Corruption (English)](https://github.com/Medabots/medarot3/assets/2187686/c28e0b93-9058-4bb1-9988-e79cae261331) |

**Comment by VariantXYZ** [comment]
Tilemap 0124
Attribmap 0123

**Comment by VariantXYZ** [comment]
![image](https://github.com/Medabots/medarot3/assets/3066132/aa754063-2c27-4a5b-9493-cc9c38e32476)
