### ISSUE TITLE
Translate the monochrome GB error message

### ISSUE THREAD

**Issue by Blaziken257** [Medabots/medarot3#182]
Medarot 3 is a GBC exclusive game and is not compatible with the monochrome Game Boy (including the original, GB Pocket, and SGB). Like other GBC exclusive games, when attempting to boot the game on a monochrome GB, an error message appears telling the user to play the game on a GBC.

This should be translated to English.

![DMG Error Message](https://github.com/Medabots/medarot3/assets/2187686/f36e1837-92d4-4b0f-a642-4f1aa8b39d01)

**Comment by VariantXYZ** [comment]
Tilemap 000A, no attribute map
