### ISSUE TITLE
Translate the paint shop menu

### ISSUE THREAD

**Issue by Blaziken257** [Medabots/medarot3#185]
There is a paint shop located in a building in Medaropolis. There is a menu with text that needs to be translated to English since it has garbled text. In addition, the ペーント graphic should be translated, and don't forget the Japanese text to the left of the money value (Dialog in yellow text boxes is already translated.)

| Japanese | English |
| ------------- | ------------- |
| ![bgb01225](https://github.com/Medabots/medarot3/assets/2187686/f8ed554f-93a4-4ced-aac3-57e7f2a0a821) | ![bgb01228](https://github.com/Medabots/medarot3/assets/2187686/b8a8b6ed-5879-45e3-872d-cbfdaee57aa9) |
| ![bgb01227](https://github.com/Medabots/medarot3/assets/2187686/adb131c3-4ea3-4104-b9ba-13e4addd6d80) | ![bgb01229](https://github.com/Medabots/medarot3/assets/2187686/265bdd51-a421-45f5-af2d-f7df05f9f081) |

In addition, this screen has a 8x8 font for your Medabot (see "Metabee" in this example) which doesn't match the Robattle preview screen.

![bgb01221](https://github.com/Medabots/medarot3/assets/2187686/3ae664dc-5d38-4a18-b6c8-2068322fa593)
A save file is attached which is right next to the paint shop.
[Medarot 3 - Kabuto - Paint Shop.zip](https://github.com/Medabots/medarot3/files/11765407/Medarot.3.-.Kabuto.-.Paint.Shop.zip)

**Comment by VariantXYZ** [comment]
```
Paint                Money    3700 Yen
Restore Color        Paint
Listen to Explanation
Exit
```

```
            Money    3700 Yen
            Paint
Color Select
No./ 1
```
