### ISSUE TITLE
Shop metasprite sometimes doesn't show up before chat

### ISSUE THREAD

**Issue by VariantXYZ** [Medabots/medarot3#197]
https://github.com/Medabots/medarot3/assets/3066132/a7454430-2e55-4eec-81c8-195f4ba8ab6c

https://github.com/Medabots/medarot3/assets/3066132/3cb7c87a-8a5a-4acd-8e01-1ddc5ddc1b2d

**Comment by Blaziken257** [comment]
This issue exists as far back as 0.1.0.

**Comment by VariantXYZ** [comment]
> This issue exists as far back as 0.1.0.

It might be timing related to VWF itself. 

Can do a git bisect again to see where it breaks...
