### ISSUE TITLE
Frogger mini-game uses old numeric tileset from Japanese version

### ISSUE THREAD

**Issue by Blaziken257** [Medabots/medarot3#198]
The Frogger mini-game uses the old numeric tileset from the Japanese version. The most noticeable thing about this is that the Japanese tileset is one pixel lower which is misaligned with the rest of the text.

![M3 Frogger English](https://github.com/Medabots/medarot3/assets/2187686/09d2d603-dfd8-4449-985a-b0014a6c328d)

The boat mini-game doesn't have this issue and uses the English tileset that the rest of the patch uses.

![M3 Boat English](https://github.com/Medabots/medarot3/assets/2187686/93a9140e-966d-4226-9f8d-f9762e8615f6)

A save state is attached to this issue, from the 0.4.3+EN+nightly.20230722 release in BGB 1.5.10 64-bit.
[Medarot 3 - Kabuto Version (Japan) (EN 0.4.3-20230721).sn1.zip](https://github.com/Medabots/medarot3/files/12137147/Medarot.3.-.Kabuto.Version.Japan.EN.0.4.3-20230721.sn1.zip)

**Comment by VariantXYZ** [comment]
It's using numbers from Tileset39E1. Easiest way is probably to just replace the numbers in the tileset.
