### ISSUE TITLE
Suggestion: Add info in the intro for patch information

### ISSUE THREAD

**Issue by Blaziken257** [Medabots/medarot3#212]
It might be a good idea add patch info which would let users know where to find the latest patch for Medarot 3. The English translations for Medarot 1 and Telefang do this in different ways (adding text to the continue menu for Medarot 1, or adding a separate splash screen for Telefang). Below are screenshots showing how each English translation implements this.

| Medarot 1 | Telefang |
| ------------- | ------------- |
| ![Medarot_1_Options_2x](https://github.com/Medabots/medarot3/assets/2187686/f156c439-7751-4916-913d-e643cb493b84) | ![Telefang_Opening_Credits_Tulunk_2x](https://github.com/Medabots/medarot3/assets/2187686/f6e2e597-0c67-408f-a1bc-46ef03ddd38c) |

**Comment by VariantXYZ** [comment]
Version information is now displayed on the initial menu screen, but there isn't as much space to include a disclaimer like we did for M1.

@andwhyisit mentioned we should probably have a splash screen, but I don't think we really have a site other than the repository.
