### ISSUE TITLE
Text ending in italic font affects Medarotch/Save text

### ISSUE THREAD

**Issue by Blaziken257** [Medabots/medarot3#227]
### Summary

When viewing a text string that ends in italic, and you immediately open the menu and go to Medarotch -> Medarots, Medarotch -> Medals, or Save, italic text can briefly be seen. It fixes itself afterwards and can only be seen once.

This is unrelated the now fixed issue #225; it appears in 20240117 and other, older builds that have text that end in italic.

A screenshot (for the first example) is shown below -- See that "Metabee" is in italic. (The latter two examples aren't shown but are similar.)

A save file is attached; move down and you will see the text and be able to reproduce the bug.

![M3 Italic Issue 2a](https://github.com/Medabots/medarot3/assets/2187686/75c22644-c4f8-4a17-9cbe-bf4bacb25b20) ![M3 Italic Issue 2b](https://github.com/Medabots/medarot3/assets/2187686/be4db4f6-ccc5-47bf-a5a9-395248afcdb7)
[Medarot 3 - Kabuto Version (Japan) (EN 20240117).zip](https://github.com/Medabots/medarot3/files/13960223/Medarot.3.-.Kabuto.Version.Japan.EN.20240117.zip)

**Comment by VariantXYZ** [comment]
Fixed by #228
