### ISSUE TITLE
Long part descriptions -- particularly problematic in shops

### ISSUE THREAD

**Issue by Blaziken257** [Medabots/medarot3#232]
### Version

Seen in tr_EN+nightly.20240304 but possibly occurs in earlier versions too (but untested).

### Description

Some parts have long descriptions that don't fit in two lines. In the parts screen, this is not too problematic since the player can just press A to advance the text. However, this isn't possible in shops, because pressing A gives a prompt to buy or sell parts before the text can finish.
An example is shown with the Tricky part but this can occur with other parts too.

![bgb06949](https://github.com/Medabots/medarot3/assets/2187686/2e7a388c-59f4-4414-b88f-7ff5ff6c1263)![bgb06950](https://github.com/Medabots/medarot3/assets/2187686/c53b0994-2f68-4e5e-b8d3-8a9cb159c573)
![bgb06951](https://github.com/Medabots/medarot3/assets/2187686/0405fd8c-906c-4318-a8dd-b1ba98ade1d7)![bgb06952](https://github.com/Medabots/medarot3/assets/2187686/aee7e0fd-a6b4-40ac-a742-7bd0a4d63a02)

In addition, the text advancement indicator on the bottom right (the best indicator that the desciption is more than two lines) only appears inconsistently. Keep selecting and unselecting the problematic part and another part back and forth using the D-Pad, and it either persists being visible all the time or never being visible. It is likely that this particular screen wasn't designed to even support more than 2 lines of text.

A save file is attached right inside a shop. While this shop doesn't let you _buy_ parts that have long descriptions, you can use the debug feature with Select to eventually find one that does have problematic parts.
[Medarot 3 - Kabuto Version (Japan) (EN 20240304) - Shop.zip](https://github.com/Medabots/medarot3/files/14624952/Medarot.3.-.Kabuto.Version.Japan.EN.20240304.-.Shop.zip)

**Comment by VariantXYZ** [comment]
Partially resolved by #233 

Indicator still needs to be fixed

**Comment by Blaziken257** [comment]
This issue also happens to be present in the screen where you can view your Medabots. A save is provided to show an example. Press B -> Medarots -> Saurus -> Steam Dolin or Steam Pipe to see it.

![bgb07562](https://github.com/Medabots/medarot3/assets/2187686/614720c7-55e8-4476-9aed-77838828d457)

[Medarot 3 - Kabuto Version (Japan) (EN 20240406) - Steam Pipe.zip](https://github.com/Medabots/medarot3/files/14894946/Medarot.3.-.Kabuto.Version.Japan.EN.20240406.-.Steam.Pipe.zip)

**Comment by VariantXYZ** [comment]
https://github.com/Medabots/medarot3/assets/3066132/8b01e6bf-6624-40d1-870b-2b572aa851d6

Multi-line descriptions should be OK now in shops and the part screen.
