### ISSUE TITLE
Winning a mandatory robattle crashes the game

### ISSUE THREAD

**Issue by Blaziken257** [Medabots/medarot3#234]
### Versions

First occurred in tr_EN+nightly.20240304 and still remains as of tr_EN+nightly.20240318. Tested on bgb.
Issue doesn't occur in tr_EN+nightly.20240303 or earlier.

### Description

When winning certain robattles, as soon as the robattle is over, the game crashes (and has several graphical glitches when crashing). This issue is not present when losing. One example is battling against Kogane in Chapter 3, among others. Due to this bug, it is impossible to progress past these robattles without using an earlier nightly build.

![M3 Kogane Crash](https://github.com/Medabots/medarot3/assets/2187686/e627fd40-0bba-4d19-b3b9-e62685943e1c)

### Save

A Kabuto save is attached right before the robattle against Kogane.

If you're using Metabee to robattle, to win this one, use Medachange (Shift MC) and then use Drive B followed by Drive C, and watch it crash afterwards. (Otherwise, Kogane will keep setting up traps to damage Metabee and destroy its parts... which is also the way to lose this. Losing goes to a Game Over screen as expected.)

[Medarot 3 - Kabuto Version (Japan) - Pre-Kogane.zip](https://github.com/Medabots/medarot3/files/14765909/Medarot.3.-.Kabuto.Version.Japan.-.Pre-Kogane.zip)

**Comment by VariantXYZ** [comment]
Something in the Link changes is the most likely culprit.

**Comment by VariantXYZ** [comment]
Hmm, it is something in the link patch for sure, so I'll revert it for now and reintroduce it after debugging this.

Given how it behaves differently in English (left) vs Japanese (right), it's probably a change that unintentionally corrupted some data out of bounds:
![image](https://github.com/Medabots/medarot3/assets/3066132/dc77c426-672d-4cbe-97f2-d77380c59d33)

**Comment by VariantXYZ** [comment]
Yep. I loaded something from the new text area when we didn't have anything there, and that caused some trouble.
