### ISSUE TITLE
Suggestion: Translate icons for Disable move

### ISSUE THREAD

**Issue by Blaziken257** [Medabots/medarot3#235]
When a Medabot uses Disable on an opposing Medabot, it disables a random part, and an icon shows up (seemingly a kanji) depending on which part is disabled (head, left arm, or right arm). Currently, the icons are still in Japanese. Perhaps the icons should be redrawn in the English patch (similar to the [animation for Imprison in Pokémon](https://bulbapedia.bulbagarden.net/wiki/Imprison_(move)#Core_series_games)).

| Part | Part Icon | Text |
| - | - | - | 
| Head | ![bgb07466](https://github.com/Medabots/medarot3/assets/2187686/cd350a26-326b-4f42-aaf8-033052a8c225) | ![bgb07467](https://github.com/Medabots/medarot3/assets/2187686/d7c70c7f-1c55-4f21-8f4d-4acd780ead04) |
| Left Arm | ![bgb07464](https://github.com/Medabots/medarot3/assets/2187686/78b0b9f4-76fc-4ef2-b670-96c209314b9b) | ![bgb07465](https://github.com/Medabots/medarot3/assets/2187686/60ee54f2-ccf8-4cb0-83d7-5c6792aef75a)
| Right Arm | ![bgb07462](https://github.com/Medabots/medarot3/assets/2187686/8b5ea1d6-4642-4c14-91a4-b5b1d2920c71) | ![bgb07463](https://github.com/Medabots/medarot3/assets/2187686/45fce6b6-795e-4d4b-9523-727ca49e35ad) |

As a side note, when a Medabot attempts to use a disabled part, the corresponding text isn't capitalized correctly:

![bgb07469](https://github.com/Medabots/medarot3/assets/2187686/e00776bc-ac9f-41eb-94e6-3aae544cc781) ![bgb07468](https://github.com/Medabots/medarot3/assets/2187686/9552e3df-0a39-4d1a-bfdc-6057b77e17bc) ![bgb07479](https://github.com/Medabots/medarot3/assets/2187686/3114e1bf-112b-41b7-9fae-8bb1a4d19930)

A save for the start of Under-Shell is attached below. Simply walk in the overworld until you come across a High School Girl, who has an Axolotl that frequently uses Disable.

[Medarot 3 - Kabuto Version (Japan) - Under-Shell.zip](https://github.com/Medabots/medarot3/files/14784493/Medarot.3.-.Kabuto.Version.Japan.-.Under-Shell.zip)

**Comment by VariantXYZ** [comment]
PartialTileset0119, we should be able to just modify the image here for this.

**Comment by VariantXYZ** [comment]
https://github.com/Medabots/medarot3/assets/3066132/22a1a9f5-9d43-4516-aa06-4b0c1f5126f3


https://github.com/Medabots/medarot3/assets/3066132/9eb3de10-940d-4d56-9197-b68fa5706a33


https://github.com/Medabots/medarot3/assets/3066132/2d076944-8a60-4637-a35c-06ff4d1fdf95

The translation is also updated to resolve the lower-case issue.
