### ISSUE TITLE
Empty Dialog Box when defeating ruberobo with Koji

### ISSUE THREAD

**Issue by DRAG4YOU** [Medabots/medarot3#236]
This happens on the 3rd Dialog box before Rokusho appears

![3](https://github.com/Medabots/medarot3/assets/16998974/f38656d4-f561-4b4e-8967-5c3fc1ef397d)
![4](https://github.com/Medabots/medarot3/assets/16998974/f0bfc0f4-ae7f-4c44-bc95-47beb9c602ab)

If this is intentional? Why not add some dots to represent it "..."

**Comment by Blaziken257** [comment]
There's at least another blank box in Under-Shell in part of one dialogue; a save is attached. Speak to the NPC next to Ikki to see it.

![bgb07589](https://github.com/Medabots/medarot3/assets/2187686/26429b46-8ac2-4a22-867a-d3ae6c4da466)

[Medarot 3 - Kabuto Version (Japan) (EN 20240406) - Blank text box.zip](https://github.com/Medabots/medarot3/files/14895230/Medarot.3.-.Kabuto.Version.Japan.EN.20240406.-.Blank.text.box.zip)
