### ISSUE TITLE
Text string in Under-Shell only appears briefly

### ISSUE THREAD

**Issue by Blaziken257** [Medabots/medarot3#237]
There is one specific text string that shows up for a very brief time before it skips to another line without any user input. A GIF is attached below. This is seen in tr_EN+nightly.20240404 but might occur in earlier builds.

![M3 Under-Shell Text Bug](https://github.com/Medabots/medarot3/assets/2187686/f1ccec96-d3bb-431a-89e3-de3971eeb889)

This issue isn't present in the Japanese version, which has the icon that normally appears to advance text with A.

![bgb07515](https://github.com/Medabots/medarot3/assets/2187686/3cd34118-b44c-43b9-ad34-5d680fcf5641)

A save is attached; press A to talk to the NPC with the problematic string.

[Medarot 3 - Kabuto Version (Japan) (EN 20240404).zip](https://github.com/Medabots/medarot3/files/14881552/Medarot.3.-.Kabuto.Version.Japan.EN.20240404.zip)

**Comment by Blaziken257** [comment]
Looks like this issue was fixed in 20240406.

**Comment by Blaziken257** [comment]
And while the issue with the above string was fixed, there's a similar issue with a different text string. A save is attached; enter the Merman/Mermaid Academies (go up and then left) to see it.
[Medarot 3 - Kabuto Version (Japan) (EN 20240406) - Text issue Ch4.zip](https://github.com/Medabots/medarot3/files/14895218/Medarot.3.-.Kabuto.Version.Japan.EN.20240406.-.Text.issue.Ch4.zip)

**Comment by VariantXYZ** [comment]
Resolved.
