### ISSUE TITLE
Missing names for Medabots of Medalympics teammates

### ISSUE THREAD

**Issue by Blaziken257** [Medabots/medarot3#238]
### Versions

First occurred on tr_EN+nightly.20240304 and remains in present builds; not present in tr_EN+nightly.20240303 or earlier

### Description

When other Medafighters (two of Koji, Karin, or Arika) team up with you in a Medalympics battle, the names of Medabots of your teammates don't show up. (However, your own Medabot is unaffected). This results in strings such as " used Berserk! Sword!" (See comparison screenshots below.)

### Screenshots

| Expected | Actual |
| - | - |
| ![bgb07621](https://github.com/Medabots/medarot3/assets/2187686/8f0e2b34-2034-4211-a980-33c52d46f0ab) | ![bgb07618](https://github.com/Medabots/medarot3/assets/2187686/a206d22a-0779-45dd-8ae8-2718d5b373cd) |

### Saves

Attached are a couple of example saves where this can be seen. (Presumably this occurs in all of Medalympic battles...)

[Medarot 3 - Kabuto Version (Japan) - Medalympics - Hanazono Gym.zip](https://github.com/Medabots/medarot3/files/14914988/Medarot.3.-.Kabuto.Version.Japan.-.Medalympics.-.Hanazono.Gym.zip)
[Medarot 3 - Kabuto Version (Japan) - Medalympics - Under-Shell.zip](https://github.com/Medabots/medarot3/files/14914989/Medarot.3.-.Kabuto.Version.Japan.-.Medalympics.-.Under-Shell.zip)

**Comment by VariantXYZ** [comment]
Probably related to https://github.com/Medabots/medarot3/commit/75f5db98fdfdc48920b00b06c305127c88d7f98f#diff-42fbe538e59f7215ee9691a2a4aa9849139113272b36c24478d5525418f2b9c2
