### ISSUE TITLE
Hey "Kanji" text from the merman boys

### ISSUE THREAD

**Issue by DRAG4YOU** [Medabots/medarot3#239]
Once you defeat the two merman boys and get the bubble ticket text the kid says Kanji?

![1](https://github.com/Medabots/medarot3/assets/16998974/c0ff365c-af35-4ec1-9c9d-21f2391f6d2d)
![Medarot 3 - Kuwagata Version (English 2024-04-10)](https://github.com/Medabots/medarot3/assets/16998974/263539ff-bdfe-43e7-8fcb-2903436b67f0)

[Medarot 3 - Kuwagata Version (English 2024-04-10) - Kanji.zip](https://github.com/Medabots/medarot3/files/14953885/Medarot.3.-.Kuwagata.Version.English.2024-04-10.-.Kanji.zip)

**Comment by kabuto93** [comment]
Kanji is the name of one of the boys. It is a bit disorienting having it alone in that textbox, so I added some manual formatting to break the lines differently. The affected line is 0x2081a6.
![image](https://github.com/Medabots/medarot3/assets/4658518/34c11d0c-61c3-4bc1-802f-94743eb7f4fe)
