### ISSUE TITLE
Wrong name for Karin it says Karen

### ISSUE THREAD

**Issue by DRAG4YOU** [Medabots/medarot3#240]
This appears talking with Arika

![1](https://github.com/Medabots/medarot3/assets/16998974/a10d4c22-8ec1-48d6-ab6e-9e21ab743099)

[Medarot 3 - Kuwagata Version (English 2024-04-10) - Karen.zip](https://github.com/Medabots/medarot3/files/14954331/Medarot.3.-.Kuwagata.Version.English.2024-04-10.-.Karen.zip)

Also, a space after comma here.

![2](https://github.com/Medabots/medarot3/assets/16998974/ab9e152e-f2c7-4076-a111-7908e5675146)

**Comment by VariantXYZ** [comment]
Fixed, should take effect in tomorrow's update.
