### ISSUE TITLE
The dialog of this Medarot - Subaru

### ISSUE THREAD

**Issue by DRAG4YOU** [Medabots/medarot3#241]
I don't know if this is lore accurate or correct but the way this medarot speaks seems odd.

![1](https://github.com/Medabots/medarot3/assets/16998974/9d69fd85-f692-4aec-95c0-69b7930d17fc)
![2](https://github.com/Medabots/medarot3/assets/16998974/5a1c0085-4bf0-45b8-9202-206088032da3)
![3](https://github.com/Medabots/medarot3/assets/16998974/b2ba193f-01be-46ac-be86-524255766fea)
![4](https://github.com/Medabots/medarot3/assets/16998974/daa283d9-341e-4472-9ade-693fe00e1d8e)

Specially the part that says Please be. Ful.
[Medarot 3 - Kuwagata Version (English 2024-04-13) -  Please be. Ful.zip](https://github.com/Medabots/medarot3/files/14965447/Medarot.3.-.Kuwagata.Version.English.2024-04-13.-.Please.be.Ful.zip)

Hmm... is it Please be careful.?

**Comment by VariantXYZ** [comment]
Pretty sure this is meant to reflect the broken statements of the original.

**Comment by DRAG4YOU** [comment]
> Pretty sure this is meant to reflect the broken statements of the original.

Cool I'll close this.
