### ISSUE TITLE
Medaforce menu bug

### ISSUE THREAD

**Issue by DRAG4YOU** [Medabots/medarot3#244]
I unlocked the medaforces of 3 medals and the 3rd medaforce looks like this:

![1](https://github.com/Medabots/medarot3/assets/16998974/aea08cd5-bdb0-41ee-a53f-1ea19bba3ecf)
![2](https://github.com/Medabots/medarot3/assets/16998974/381fc2b8-f778-4a5d-ad9e-8b503d15cd49)
![Medarot 3 - Kuwagata Version (English 2024-04-17)](https://github.com/Medabots/medarot3/assets/16998974/e65064b8-91fc-4459-94c8-680f9e2e61ea)

[Medarot 3 - Kuwagata Version (English 2024-04-17) - Medaforce Menu Bug.zip](https://github.com/Medabots/medarot3/files/15005200/Medarot.3.-.Kuwagata.Version.English.2024-04-17.-.Medaforce.Menu.Bug.zip)

I believe that extra "skill name" that appears at the left box should not appear because we have the right box for that.

Also, this bug is not present on the japanese version.

**Comment by VariantXYZ** [comment]
![image](https://github.com/Medabots/medarot3/assets/3066132/36f5deac-a26a-4772-9c11-4f186af94524)

Due to skill name being incorrectly mapped over the 3rd medaforce. Should be fixed in tomorrow's nightly update.
